version: '3.8'

services:
    access-db:
        image: postgres:15.10
        ports:
            - '5440:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=access
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
