version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '30002:30002'
        network_mode: host
    access-db:
        image: postgres:17.2-alpine3.21
        ports:
            - '5440:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=access
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
