// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spl-access/ent/access"
	"spl-access/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessUpdate is the builder for updating Access entities.
type AccessUpdate struct {
	config
	hooks    []Hook
	mutation *AccessMutation
}

// Where appends a list predicates to the AccessUpdate builder.
func (_u *AccessUpdate) Where(ps ...predicate.Access) *AccessUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRun sets the "run" field.
func (_u *AccessUpdate) SetRun(v string) *AccessUpdate {
	_u.mutation.SetRun(v)
	return _u
}

// SetNillableRun sets the "run" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableRun(v *string) *AccessUpdate {
	if v != nil {
		_u.SetRun(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *AccessUpdate) SetLocation(v access.Location) *AccessUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableLocation(v *access.Location) *AccessUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetEntryAt sets the "entry_at" field.
func (_u *AccessUpdate) SetEntryAt(v time.Time) *AccessUpdate {
	_u.mutation.SetEntryAt(v)
	return _u
}

// SetNillableEntryAt sets the "entry_at" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableEntryAt(v *time.Time) *AccessUpdate {
	if v != nil {
		_u.SetEntryAt(*v)
	}
	return _u
}

// SetExitAt sets the "exit_at" field.
func (_u *AccessUpdate) SetExitAt(v time.Time) *AccessUpdate {
	_u.mutation.SetExitAt(v)
	return _u
}

// SetNillableExitAt sets the "exit_at" field if the given value is not nil.
func (_u *AccessUpdate) SetNillableExitAt(v *time.Time) *AccessUpdate {
	if v != nil {
		_u.SetExitAt(*v)
	}
	return _u
}

// ClearExitAt clears the value of the "exit_at" field.
func (_u *AccessUpdate) ClearExitAt() *AccessUpdate {
	_u.mutation.ClearExitAt()
	return _u
}

// Mutation returns the AccessMutation object of the builder.
func (_u *AccessUpdate) Mutation() *AccessMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessUpdate) check() error {
	if v, ok := _u.mutation.Location(); ok {
		if err := access.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "Access.location": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(access.Table, access.Columns, sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Run(); ok {
		_spec.SetField(access.FieldRun, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(access.FieldLocation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EntryAt(); ok {
		_spec.SetField(access.FieldEntryAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExitAt(); ok {
		_spec.SetField(access.FieldExitAt, field.TypeTime, value)
	}
	if _u.mutation.ExitAtCleared() {
		_spec.ClearField(access.FieldExitAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{access.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessUpdateOne is the builder for updating a single Access entity.
type AccessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessMutation
}

// SetRun sets the "run" field.
func (_u *AccessUpdateOne) SetRun(v string) *AccessUpdateOne {
	_u.mutation.SetRun(v)
	return _u
}

// SetNillableRun sets the "run" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableRun(v *string) *AccessUpdateOne {
	if v != nil {
		_u.SetRun(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *AccessUpdateOne) SetLocation(v access.Location) *AccessUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableLocation(v *access.Location) *AccessUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetEntryAt sets the "entry_at" field.
func (_u *AccessUpdateOne) SetEntryAt(v time.Time) *AccessUpdateOne {
	_u.mutation.SetEntryAt(v)
	return _u
}

// SetNillableEntryAt sets the "entry_at" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableEntryAt(v *time.Time) *AccessUpdateOne {
	if v != nil {
		_u.SetEntryAt(*v)
	}
	return _u
}

// SetExitAt sets the "exit_at" field.
func (_u *AccessUpdateOne) SetExitAt(v time.Time) *AccessUpdateOne {
	_u.mutation.SetExitAt(v)
	return _u
}

// SetNillableExitAt sets the "exit_at" field if the given value is not nil.
func (_u *AccessUpdateOne) SetNillableExitAt(v *time.Time) *AccessUpdateOne {
	if v != nil {
		_u.SetExitAt(*v)
	}
	return _u
}

// ClearExitAt clears the value of the "exit_at" field.
func (_u *AccessUpdateOne) ClearExitAt() *AccessUpdateOne {
	_u.mutation.ClearExitAt()
	return _u
}

// Mutation returns the AccessMutation object of the builder.
func (_u *AccessUpdateOne) Mutation() *AccessMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccessUpdate builder.
func (_u *AccessUpdateOne) Where(ps ...predicate.Access) *AccessUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessUpdateOne) Select(field string, fields ...string) *AccessUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Access entity.
func (_u *AccessUpdateOne) Save(ctx context.Context) (*Access, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessUpdateOne) SaveX(ctx context.Context) *Access {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessUpdateOne) check() error {
	if v, ok := _u.mutation.Location(); ok {
		if err := access.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "Access.location": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessUpdateOne) sqlSave(ctx context.Context) (_node *Access, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(access.Table, access.Columns, sqlgraph.NewFieldSpec(access.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Access.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, access.FieldID)
		for _, f := range fields {
			if !access.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != access.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Run(); ok {
		_spec.SetField(access.FieldRun, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(access.FieldLocation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EntryAt(); ok {
		_spec.SetField(access.FieldEntryAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExitAt(); ok {
		_spec.SetField(access.FieldExitAt, field.TypeTime, value)
	}
	if _u.mutation.ExitAtCleared() {
		_spec.ClearField(access.FieldExitAt, field.TypeTime)
	}
	_node = &Access{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{access.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
