// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Access is the predicate function for access builders.
type Access func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
